# Generated by Django 5.2.6 on 2025-09-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='staff123', max_length=20, unique=True),
        ),
    ]
