# Generated by Django 5.2.6 on 2025-09-05 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0004_alter_pet_owner'),
        ('vets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('check_up', 'Check-up'), ('emergency', 'Emergency'), ('surgery', 'Surgery'), ('vaccination', 'Vaccination'), ('grooming', 'Grooming'), ('follow_up', 'Follow-up')], default='check_up', max_length=100)),
                ('notes', models.CharField(max_length=500)),
                ('pet', models.ForeignKey(default=500, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pets.pet')),
                ('vet', models.ForeignKey(default=500, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='vets.vets')),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
    ]
