# Generated by Django 5.2.6 on 2025-09-08 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointments_time_alter_appointments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='time',
            field=models.TimeField(default=datetime.time(0, 9)),
        ),
    ]
