# Generated by Django 5.2.6 on 2025-09-08 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointments_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='time',
            new_name='timetype',
        ),
    ]
