# Generated by Django 5.2.6 on 2025-09-08 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_rename_time_appointments_timetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='timetype',
            new_name='time',
        ),
    ]
