# Generated by Django 5.2.6 on 2025-09-09 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_rename_timetype_appointments_time'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='owner',
            field=models.ForeignKey(default=500, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='owner.owner'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='payment_method',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='payment_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('refund', 'Refund')], default='pending', max_length=100),
        ),
    ]
