# Generated by Django 5.2.6 on 2025-09-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vets',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
