# Generated by Django 5.2.6 on 2025-09-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.IntegerField(max_length=8)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone', models.IntegerField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'owners',
            },
        ),
    ]
