# Generated by Django 5.2.6 on 2025-09-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.IntegerField(max_length=100, unique=True),
        ),
    ]
