# Generated by Django 5.2.6 on 2025-09-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_owner_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
