# Generated by Django 5.2.6 on 2025-09-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('animal_type', models.CharField(choices=[('bird', 'Bird'), ('cat', 'Cat'), ('dog', 'Dog'), ('ferret', 'Ferret'), ('rabbit', 'Rabbit')], default='cat', max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('color', models.CharField(default='unknown', max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('neutered_spayed', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'pets',
            },
        ),
    ]
