# Generated by Django 5.2.6 on 2025-09-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='animal_type',
            field=models.CharField(choices=[('bird', 'Bird'), ('cat', 'Cat'), ('dog', 'Dog'), ('ferret', 'Ferret'), ('rabbit', 'Rabbit')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
