# Generated by Django 5.2.6 on 2025-09-04 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pet',
            table='pets',
        ),
    ]
