# Generated by Django 5.2.6 on 2025-09-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_animal_type_alter_pet_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animal_type',
            field=models.CharField(choices=[('bird', 'Bird'), ('cat', 'Cat'), ('dog', 'Dog'), ('ferret', 'Ferret'), ('rabbit', 'Rabbit')], default='cat', max_length=50),
        ),
    ]
