# Generated by Django 5.2.6 on 2025-09-05 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
        ('pets', '0003_pet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(default=500, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='owner.owner'),
        ),
    ]
